apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit-cm
  namespace: argocd-test
data:
  filter.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE filter.conf
    @INCLUDE input.conf
    @INCLUDE output.conf
  input.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            kub-logs
        Refresh_Interval  5
        Mem_Buf_Limit     20MB
        Skip_Long_Lines   On
  output.conf: |
    [OUTPUT]
        name stdout
        match *
  parsers.conf: |
    [PARSER]
        Name        kub-logs
        Format      json
