apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit-cm
  namespace: argocd-test
data:
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
    [OUTPUT]
        Name stdout
        Format json
