apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit-cm
  namespace: argocd-test
data:
  convert_date.lua: |-
    function convert_date_efs(tag, timestamp, record)
      local pattern = "(%d+)-(%d+)-(%d+) (%d+):(%d+):(%d+),(%d+)"
      dt_str = record["serverEventDatetime"]
      local year, month, day, hour, minute, seconds, milliseconds = dt_str:match(pattern)
      ts = os.time{year = year, month = month, day = day, hour = hour, min = minute, sec = seconds }
      ts = (ts * 1000) + milliseconds
      record["serverEventDatetime"] = ts
      return 2, timestamp, record
    end
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
  fluent-bit.conf: |
    [SERVICE]
        Flush 5
        Daemon Off
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
    [FILTER]
        Name    lua
        Match   *
        script  /fluent-bit/etc/convert_date.lua
        call    convert_date_efs
    [INPUT]
        Name tail
        Path /var/log/containers/*argocd-test_guestbook-ui*.log
        Tag kube.*
        Parser docker
    [OUTPUT]
        Name stdout
        Match *
